### ISSUE TITLE
Player lag when eat golden apple and get hit

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#31]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version: Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: LINUX
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)
0:42:49 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in /root/fame/src/pocketmine/entity/Entity.php on line 924" (EXCEPTION) in "/src/pocketmine/entity/Living" at line 100
00:42:49 [NOTICE] Blocked ip.of.the.player for 5 seconds

**Comment by CortexPE** [comment]
Hmm. I'll try my best to test this.

**Comment by TDMidkwhatisxd** [comment]
This is fixed on PMMP api3/blocks branch. You should fork that branch not master.

**Comment by CortexPE** [comment]
Can someone test this Now?
I ported the Fixed part from the api3/blocks branch.

**Comment by XDqrkneZ** [comment]
Nope, still get the error.


18:57:19 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in /root/fame/src/pocketmine/entity/Entity.php on line 961" (EXCEPTION) in "/src/pocketmine/entity/Living" at line 100

I can help you test it to see it yourself

**Comment by CortexPE** [comment]
Can u try it now?

**Comment by XDqrkneZ** [comment]
@CortexPE worked!!!!!!!!!!!! You are a flippin legend
